apiVersion: apps/v1
kind: Deployment
metadata:
  name: skipper
spec:
  template:
    spec:
      containers:
      - name: skipper
        volumeMounts:
          - name: broker
            mountPath: /workspace/runtime/secrets/broker
            readOnly: true
      volumes:
        - name: broker
          secret:
            secretName: rabbitmq
            items:
            - key: rabbitmq-password
              path: broker-password 
