apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: prometheus-proxy-httpproxy
  namespace: monitoring-tools
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: prometheus-proxy
      port: 8080
  virtualhost:
    fqdn: prometheus-proxy.tanzudata.ml